pipeline {
    agent {
        docker {
            image 'elirenato2000/java11_pg13'
            args '-e POSTGRES_PORT="127.0.0.1:5432:5432" -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_HOST_AUTH_METHOD=password -e POSTGRES_INITDB_ARGS="--auth-host=password" -e POSTGRES_DATABASES="app_test,app_test_user,password" -v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'mvn test -Dtest.containers.disabled'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
//         stage('Build') {
//             steps {
//                 sh 'mvn -B -DskipTests clean package'
//             }
//         }
//         stage('Deliver') {
//             steps {
//                 sh './jenkins/scripts/deliver.sh'
//             }
//         }
    }
}